import { GetServerSideProps, NextPage } from "next";
import { AxiosError } from "axios";
import { DetailsPage } from "@/types/pages";
import { Error } from "@/constants/Errors";
import Head from "next/head";
import CurrenciesDetails from "@/components/CurrenciesDetails";
import {fetchCurrenciesDetails} from "@/services/currencies";
import { DefaultQuery } from "@/constants/Query";

const Details: NextPage<DetailsPage> = ({ details }) => {
    console.log(details,'client')
    return (
        <>
            <Head>
                <title>Interview Task</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <CurrenciesDetails items={details} />
        </>
    );
};

export const getServerSideProps: GetServerSideProps = async ({
    query: { vs_currency, page, per_page, price_change_percentage },
}) => {
    try {
        const details = await fetchCurrenciesDetails({
            vs_currency: vs_currency || DefaultQuery.vs_currency,
            page: page || DefaultQuery.page,
            per_page: per_page || DefaultQuery.per_page,
            price_change_percentage: price_change_percentage || DefaultQuery.price_change_percentage,
        });
        console.log(details,'server')

        return {
            props: {
                details,
            },
        };
    } catch (e: AxiosError | any) {
        return {
            props: {
                error: {
                    status: e.status || Error.status,
                    message: e.message || Error.message,
                },
            },
        };
    }
};

export default Details;
