import { GetServerSideProps, NextPage } from "next";
import { AxiosError } from "axios";
import { Error } from "@/constants/Errors";
import Head from "next/head";
import { fetchSupportedCurrenciesList } from "@/services/currencies";
import CurrenciesList from "@/components/CurrenciesList";
import {dehydrate, QueryClient, } from "@tanstack/react-query";
import {QueryKeys} from "@/enums/query";
import {PageError} from "@/types/errors";

const Currencies: NextPage<PageError> = ({ error }) => {

    return (
        <>
            <Head>
                <title>Interview Task</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <CurrenciesList/>
        </>
    );
};

export const getServerSideProps: GetServerSideProps = async () => {

    try {
        const queryClient = new QueryClient()

        await queryClient.prefetchQuery([QueryKeys.CURRENCIES_LIST], fetchSupportedCurrenciesList)

        return {
            props: {
                dehydratedState: dehydrate(queryClient),
            },
        };
    } catch (e: AxiosError | any) {
        return {
            props: {
                error: {
                    status: e.status || Error.status,
                    message: e.message || Error.message,
                },
            },
        };
    }
};

export default Currencies;
