import { GetServerSideProps, NextPage } from "next";
import { AxiosError } from "axios";
import { HomePage } from "@/types/pages";
import { Error } from "@/constants/Errors";
import Head from "next/head";
import { fetchSupportedCurrenciesList } from "@/services/currencies";
import CurrenciesList from "@/components/CurrenciesList";

const Currencies: NextPage<HomePage> = ({ currencies }) => {
    return (
        <>
            <Head>
                <title>Interview Task</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <CurrenciesList items={currencies} />
        </>
    );
};

export const getServerSideProps: GetServerSideProps = async () => {
    try {
        const currencies = await fetchSupportedCurrenciesList();

        return {
            props: {
                currencies,
            },
        };
    } catch (e: AxiosError | any) {
        return {
            props: {
                error: {
                    status: e.status || Error.status,
                    message: e.message || Error.message,
                },
            },
        };
    }
};

export default Currencies;
